-- Keep a log of any SQL queries you execute as you solve the mystery.
-- Crime data: It took place in July 28 at Humphrey Street
SELECT description FROM crime_scene_reports WHERE id IN (SELECT id FROM crime_scene_reports WHERE month = 7 AND day = 28 AND street = 'Humphrey Street');
-- After reading the description of the crime 297 it's confiormed that it matched with the duck crime.
-- From the description the bakery was mentioned to be involved time 10:15am.
-- There where 3 witness
SELECT name, transcript, year FROM interviews WHERE month = 7 AND day = 28;
-- The 3 witness where Ruth, Eugene, and Raymond,
-- From Ruth we get that the car left 10 mins from 10:15 thus 10:25 am
-- From Eugene we get that thief withdraw money earlier at Leggett Street
-- From Raymond we get that the thief called someone for less than a min
-- and they where planning to tak of the next day out of Fiftyville
-- the ticket was purchased with the receiver phone number
SELECT name FROM people WHERE license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND minute < 25 AND activity = 'exit');
-- The people that where in the bakery during the crime time frame
SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7));
-- The people that made a withdrawn earlier the day of the crime at Leggett Street
SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND minute < 25 AND activity = 'exit');
-- Finds both the people that where at bakery during the crime and the ones that withdraw money earlier at Leggett Street
Select phone_number, name FROM people WHERE name IN(SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'));
-- We get name and number of people previously mentioned
SELECT phone_number, name FROM people WHERE phone_number IN (SELECT receiver FROM phone_calls WHERE caller IN(Select phone_number FROM people WHERE name IN(SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 61);
-- From this we get the number & name of people called for a min of duration
SELECT flight_id FROM passengers WHERE passport_number IN(SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT receiver FROM phone_calls WHERE caller IN(Select phone_number FROM people WHERE name IN(SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 61)));
-- The id that are bought under the callers that had a min called with suspects
SELECT destination_airport_id, day, month FROM flights WHERE id IN (SELECT flight_id FROM passengers WHERE passport_number IN(SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE caller IN(Select phone_number FROM people WHERE name IN(SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 61)))) AND day = 29 AND month = 7;
-- From this we get the destination airport id
SELECT id FROM airports WHERE id IN (SELECT destination_airport_id FROM flights WHERE (id IN (SELECT flight_id FROM passengers WHERE passport_number IN(SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE caller IN(Select phone_number FROM people WHERE name IN(SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 61))))) AND day = 29 AND month = 7)AND city != 'Fiftyville';
-- We get the destination of the flight which is: New York City & Boston
SELECT name from people WHERE passport_number IN(SELECT passport_number FROM passengers WHERE flight_id IN(SELECT id FROM flights WHERE destination_airport_id IN(SELECT id FROM airports WHERE id IN (SELECT destination_airport_id FROM flights WHERE (id IN (SELECT flight_id FROM passengers WHERE passport_number IN(SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE caller IN(Select phone_number FROM people WHERE name IN(SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN(SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND day = 28 AND month = 7)) AND license_plate IN(SELECT license_plate FROM bakery_security_logs WHERE day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 61))))) AND day = 29 AND month = 7)AND city != 'Fiftyville')));
-- Get's the name of the people that are traveling to those two places
SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND minute < 25 AND activity = 'exit') INTERSECT SELECT name FROM people WHERE passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE destination_airport_id IN (SELECT id FROM airports WHERE id IN (SELECT destination_airport_id FROM flights WHERE id IN (SELECT flight_id FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE caller IN (SELECT phone_number FROM people WHERE name IN (SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 60))))) AND year = 2023 AND day = 29 AND month = 7 AND city != 'Fiftyville')));
-- Compares the people from the flights with the ones at the bakery during crime that also withdraw money from atm earlier at Leggett Street
SELECT city FROM airports WHERE id IN(SELECT destination_airport_id FROM flights WHERE id IN(SELECT flight_id FROM passengers WHERE passport_number IN(SELECT passport_number FROM people where name = (SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit') INTERSECT SELECT name FROM people WHERE passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE destination_airport_id IN (SELECT id FROM airports WHERE id IN (SELECT destination_airport_id FROM flights WHERE id IN (SELECT flight_id FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE caller IN (SELECT phone_number FROM people WHERE name IN (SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 60))))) AND year = 2023 AND day = 29 AND month = 7 AND city != 'Fiftyville')))))));
-- This is the destination city of the thief : New York City
SELECT name FROM people WHERE passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN(SELECT id FROM flights WHERE day = 29 AND month = 7 AND destination_airport_id IN (SELECT id FROM airports WHERE city = (SELECT city FROM airports WHERE id IN(SELECT destination_airport_id FROM flights WHERE id IN(SELECT flight_id FROM passengers WHERE passport_number IN(SELECT passport_number FROM people where name = (SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit') INTERSECT SELECT name FROM people WHERE passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE destination_airport_id IN (SELECT id FROM airports WHERE id IN (SELECT destination_airport_id FROM flights WHERE id IN (SELECT flight_id FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE phone_number IN (SELECT phone_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE caller IN (SELECT phone_number FROM people WHERE name IN (SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Leggett Street' AND year = 2023 AND day = 28 AND month = 7)) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE year = 2023 AND day = 28 AND month = 7 AND hour = 10 AND minute > 15 AND activity = 'exit'))) AND duration < 60))))) AND year = 2023 AND day = 29 AND month = 7 AND city != 'Fiftyville')))))))))));
-- This people are going to New York City on the 29th of July
-- When comparing the people flying to NYC in the 29th and the people that where at crime scene at 10 am left within 10 min and withdrawn earlier at Leggett Street we get the name of BRUCE
SELECT phone_number, name FROM people WHERE phone_number IN (SELECT receiver FROM phone_calls WHERE caller IN(Select phone_number FROM people WHERE name = 'Bruce') AND year = 2023 AND day = 28 AND month = 7 AND duration < 60);
-- From this we get the number and name of the accomplice: Robin, (375) 555-8161.
